spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aigen?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  ai:
    openrouter:
      base-url: https://openrouter.ai/api/v1
      api-key: ${OPENROUTER_API_KEY:}
      model: ${OPENROUTER_MODEL:meta-llama/llama-3.1-8b-instruct}
  servlet:
    multipart:
      # 개별 파일의 최대 크기를 100MB로 설정합니다.
      max-file-size: 4MB
      # 한 번의 요청에 포함된 모든 파일의 총 크기를 100MB로 설정합니다.
      max-request-size: 32MB
r2:
  accessKey: ${CLOUDFLARE_ACCESS_KEY_ID}
  secretKey: ${CLOUDFLARE_SECRET_ACCESS_KEY}
  endpoint: ${CLOUDFLARE_ENDPOINT}
  bucket: ${CLOUDFLARE_BUCKET}
  public-base: ${CLOUDFLARE_PUBLIC_BASE}
  region: auto
app:
  video:
    ffmpegPath: C:\\ffmpeg\\bin\\ffmpeg.exe
    width: 1080
    height: 1920
    fontPath: C:\\my_fonts\\static\\NotoSansKR-Regular.ttf
    # 이미지 한 장당 표시 시간(초)
    secondsPerImage: 2

#google:
#  cloud:
#          # 1. Google Cloud 프로젝트 ID
#    project-id: round-terminus-469507-q5
#
#          # 2. API를 호출할 리전 (Veo 모델용)
#    location: us-central1
#
#          # 3. 사용할 Vertex AI 모델 ID
#    model: veo-3.0-fast-generate-001
#
#          # 4. 서비스 계정 인증 키 파일 위치
#    credentials:
#      file: classpath:vertexId.json
#
#          # 5. Spring Cloud GCP 설정
#    gcp:
#      storage:
#              # GCS 버킷 이름 (사용자가 업로드한 파일 저장용)
#        bucket-name: "aigen-video-images"
##    database-platform: