spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aigen?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  ai:
    openrouter:
      base-url: https://openrouter.ai/api/v1
      api-key: ${OPENROUTER_API_KEY:}
      model: ${OPENROUTER_MODEL:meta-llama/llama-3.1-8b-instruct}

#    database-platform: