spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aigen?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#    database-platform:

ai:
  gemini:
    base-url: https://generativelanguage.googleapis.com
    api-key: ${GEMINI_API_KEY:}
    model: gemini-2.0-flash



logging:
  level:
    AiGEN.AiGEN: DEBUG


