spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aigen_prod?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: A!gen1313
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  ai:
    openrouter:
      base-url: https://openrouter.ai/api/v1
      api-key: ${OPENROUTER_API_KEY:}
      model: ${OPENROUTER_MODEL:meta-llama/llama-3.1-8b-instruct}
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 32MB
ai:
  gemini:
    base-url: https://generativelanguage.googleapis.com
    api-key: ${GEMINI_API_KEY:}
    model: ${GEMINI_MODEL:gemini-2.0-flash}
r2:
  accessKey: ${CLOUDFLARE_ACCESS_KEY_ID}
  secretKey: ${CLOUDFLARE_SECRET_ACCESS_KEY}
  endpoint: ${CLOUDFLARE_ENDPOINT}
  bucket: ${CLOUDFLARE_BUCKET}
  public-base: ${CLOUDFLARE_PUBLIC_BASE}
  region: auto
app:
  video:
    ffmpegPath: /usr/local/bin/ffmpeg
    width: 1080
    height: 1920
    fontPath: /opt/fonts/NotoSansKR-Regular.ttf
    secondsPerImage: 2

